project/core/urls.py
# -*- encoding: utf-8 -*-


from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),  # Django admin route
    path('tickets/', include('tickets.urls')),  # Ticket routes - Create, list, detail
    path('groups/', include('groups.urls')),     # Grouping of tickets and users (group, project)
    path("", include("accounts.urls")),              # UI Kits Html files, Auth routes - login / register
]

# Required to use the django debug toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls))
                  ] + urlpatterns

project/tickets/urls.py
from django.urls import path

from . import views


app_name = 'tickets'

urlpatterns = [
    path('', views.TicketsListView.as_view(), name='default'),
    path('list/', views.TicketsListView.as_view(), name='list'),
    path('create/', views.TicketCreateView.as_view(), name='create'),
    path('<int:pk>/', views.TicketDetailView.as_view(), name='detail'),
]

project/tickets/models.py
# tickets/base_entity.py

from django.db import models
from django.urls import reverse

import misaka

from appsutils.models import BaseEntity
from groups.models import Group


# Create your models here.
class Ticket(BaseEntity):
    summary = models.CharField(max_length=100)
    status = models.CharField(max_length=100, default='new')
    description = models.TextField()
    description_html = models.TextField(editable=False)     # For html rendering of the description
    group = models.ForeignKey(Group, related_name="tickets", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.summary

    def save(self, *args, **kwargs):
        self.description_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_on']

project/tickets/views.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from . import models


# Create your views here.
class TicketCreateView(generic.CreateView):
    model = models.Ticket
    fields = ('summary', 'description', 'author_name')
    success_url = reverse_lazy('tickets:list')

    # def get_success_url(self):
    #     return reverse('lawyer_detail', kwargs={'lawyer_slug': self.object.lawyer_slug})

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     # self.object.user = self.request.user
    #     self.object.save()
    #     return super().form_valid(form)


class TicketsListView(generic.ListView):
    model = models.Ticket


class TicketDetailView(generic.DetailView):
    model = models.Ticket

project/tickets/templates/tickets/_ticket.html
<div class="media">

	<div class="media-body">
		<strong>{{ ticket.id }}</strong>
		<h5>Ticket summary: {{ ticket.summary }}</h5>
		<h5>Ticket description:{{ ticket.description }}</h5>
		<h5>Ticket created: {{ ticket.created_on }}</h5>

		<div class="media-footer">
				<a href="#" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
		</div>
	</div>
</div>

project/tickets/templates/tickets/ticket_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

project/tickets/templates/tickets/ticket_form.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Create new ticket {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link href="{% static 'assets/css/dashboard-free.min.css' %}" rel="stylesheet" />
{% endblock stylesheets %}

{% block content %}
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
			<h4>Create New Ticket</h4>
			<div class="tab-content">
				<div id="inputs-component" class="tab-pane tab-example-result fade show active" role="tabpanel" aria-labelledby="inputs-component-tab">
					<form method="POST" action="{% url 'tickets:create' %}" id="ticketForm">
						{% csrf_token %}
						{{ form.as_p }}


						<input type="submit" class="btn btn-primary btn-large" value="Save" />

					</form>
				</div>
			</div>
			</div>
		</div>
	</div>
{% endblock %}

project/tickets/templates/tickets/ticket_list.html
{% extends 'layouts/base.html' %}

{% block title %} List of tickets {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="col-md-8">
	{% for ticket in ticket_list %}
  {% include "tickets/_ticket.html" %}
	{% endfor %}
</div>
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}